import { strict as assert } from "node:assert";
import { readFile } from "node:fs/promises";

const main = await readFile(new URL("../web/src/main.tsx", import.meta.url), "utf8");
const home = await readFile(new URL("../web/src/IntentHome.tsx", import.meta.url), "utf8");
const threadApi = await readFile(new URL("../web/src/threadApi.ts", import.meta.url), "utf8");
const onboarding = await readFile(new URL("../web/src/IntentOnboarding.tsx", import.meta.url), "utf8");
const rooms = await readFile(new URL("../web/src/ChannelRoomsFeature.tsx", import.meta.url), "utf8");

assert.match(main, /localStorage\.getItem\("chef:surface"\) === "workbench" \? "workbench" : "home"/, "fresh Chef sessions should default to the intent home");
assert.match(main, /if \(surface === "home"\)/, "home and Workbench must be explicit product surfaces");
assert.match(main, /<IntentHome onOpenWorkbench=\{openWorkbench\} \/>/, "the default surface should mount the intent-first home");
assert.match(main, /<IntentOnboarding \/>/, "the default Home should mount the first-run happy-path onboarding");
assert.match(main, /<App key=\{viewMode\} \/>/, "the existing graph UI should remain available as the Workbench");
assert.match(main, /<ChannelRoomsFeature \/>/, "Rooms should remain available from the Workbench depth");
assert.match(home, /What are we doing\?/, "the home should lead with user intent rather than graph controls");
assert.match(home, /listThreads\(\)/, "Simple Mode must load durable workspace Threads");
assert.match(home, /threadMessages\(selected\.id\)/, "Simple Mode history must come from the selected Thread");
assert.match(home, /sendThreadMessage\(threadId, message\)/, "the primary composer must continue work through the selected Thread");
assert.match(home, /\+ New thread/, "Thread creation must be available directly from Simple Mode");
assert.match(home, /createThread\("New thread"\)/, "Simple Mode must be able to create an explicit new Thread");
assert.match(home, /renameSelectedThread\(\)/, "Thread rename must be available directly from Home");
assert.match(home, /archiveSelectedThread\(\)/, "Thread archive must be available directly from Home");
assert.match(home, /nextThreads\.find\(\(thread\) => thread\.status === "active"\)/, "archiving the selected Thread must move selection to another active Thread when possible");
assert.match(home, /saveSelectedThreadId\(nextActive\?\.id \?\? null\)/, "archiving must not leave an archived Thread persisted as the active selection");
assert.match(home, /mission\.metadata\?\.threadId === selectedThreadId/, "Mission status on Home must be scoped to the selected Thread");
assert.match(home, /const missionChronology = useMemo/, "Home must derive one stable Mission chronology for current work and history");
assert.match(home, /sort\(\(a, b\) => b\.createdAt - a\.createdAt\)/, "Mission chronology must follow creation time instead of mutation time");
assert.doesNotMatch(home, /sort\(\(a, b\) => b\.updatedAt - a\.updatedAt\)/, "updating an older Mission must not make it current again");
assert.match(home, /const latestMission = missionChronology\[0\] \?\? null;/, "current work must use the newest created Mission in the selected Thread");
assert.match(home, /const recentPriorMissions = useMemo/, "Home must derive bounded prior Mission history from the selected Thread projection");
assert.match(home, /missionChronology\s+\.filter\(\(mission\) => mission\.id !== latestMission\?\.id\)/, "prior Mission history must share the same creation chronology as current work");
assert.match(home, /mission\.id !== latestMission\?\.id/, "prior Mission history must not duplicate the current Mission");
assert.match(home, /\.slice\(0, 3\)/, "prior Mission history must stay bounded on the default Home surface");
assert.match(home, /Recent Mission outcomes/, "selected Thread prior outcomes must be inspectable without opening Workbench");
assert.match(home, /missionOutcomePresentation\(mission\.status\)/, "prior Mission history must use human-readable outcome labels");
assert.match(home, /Recent conversation/, "selected Thread history must be visible without opening Workbench");
assert.match(home, /saveSelectedThreadId/, "selected Thread should survive reload when possible");
assert.match(threadApi, /method: "PATCH"/, "Thread rename must use the existing PATCH lifecycle route");
assert.match(threadApi, /\/api\/threads\/\$\{encodeURIComponent\(threadId\)\}\/archive/, "Thread archive must use the canonical archive route");
assert.match(threadApi, /\/api\/threads\/\$\{encodeURIComponent\(threadId\)\}\/chat/, "Thread sends must use the canonical Thread-scoped endpoint");
assert.match(threadApi, /\/api\/threads\/\$\{encodeURIComponent\(threadId\)\}\/messages/, "Thread history must use the canonical Thread-scoped endpoint");
assert.doesNotMatch(home, /api\.chat\(|api\.chatMessages\(/, "Simple Mode must not silently fall back to workspace-global chat continuity");
assert.match(home, /Open Workbench/, "advanced inspection should stay deliberately reachable");
assert.match(home, /Needs your attention/, "approval and failure states should be surfaced in plain language");
assert.match(home, /const threadTaskIds = useMemo/, "Home must derive the selected Thread's task lineage before projecting approvals");
assert.match(home, /threadMissions\.flatMap\(\(mission\) => mission\.taskIds\)/, "approval lineage must include every Mission in the selected Thread, not only the latest Mission");
assert.match(home, /const missionByTaskId = useMemo/, "Home must resolve approval ownership through selected-Thread Mission task lineage");
assert.match(home, /owners\.set\(taskId, mission\)/, "each selected-Thread task must map back to its owning Mission for approval context");
assert.match(home, /missionByTaskId\.get\(approval\.taskId\)\?\.goal/, "pending approvals must carry the owning Mission goal instead of exposing raw IDs");
assert.match(home, /For this Mission/, "approval cards must identify which Mission the decision belongs to");
assert.match(home, /\{approval\.missionGoal\}/, "approval cards must render the resolved human-readable Mission goal");
assert.match(home, /approvals\s+\.filter\(\(approval\) => threadTaskIds\.has\(approval\.taskId\)\)/, "pending approvals from sibling Threads must stay excluded while earlier selected-Thread approvals remain visible");
assert.match(home, /missionApprovals\.length > 0/, "any selected-Thread pending approval must put Home into the attention state");
assert.match(home, /latestMission\?\.status === "failed"/, "Mission-level failure must put Home into the attention state even without a failed Task projection");
assert.match(home, /latestMission\?\.status === "blocked"/, "Mission-level blocked state must remain visible even without a blocked Task projection");
assert.match(home, /latestMission\?\.status === "cancelled"/, "Mission-level cancellation must not fall back to Ready when Task rows are missing or stale");
assert.match(home, /latestMission\?\.status === "waiting_for_approval"/, "Mission-level approval wait must remain visible even when the approval row has not projected yet");
assert.match(home, /latestMission\?\.status === "paused"/, "Mission-level pause must remain an attention state without depending on Task rows");
assert.match(home, /latestMission\?\.status === "planning"/, "Mission planning must keep Home in a working state before Task rows exist");
assert.match(home, /latestMission\?\.status === "active"/, "an active Mission must keep Home in a working state even between Task projections");
assert.match(home, /latestMission\?\.status === "verifying"/, "Mission verification must remain working until the Mission reaches a terminal state");
assert.match(home, /const ids = new Set\(latestMission\.taskIds\);\s+return tasks\.filter/, "current-work task rendering must remain scoped to the latest Mission");
assert.match(home, /const currentMissionTaskIds = useMemo/, "failure activity must have an explicit current-Mission task boundary");
assert.match(home, /new Set\(latestMission\?\.taskIds \?\? \[\]\)/, "failure activity must derive only from the current Mission task lineage");
assert.match(home, /setEvents\(snapshot\.events\)/, "Home must project existing durable runtime activity instead of creating a second failure store");
assert.match(home, /event\.type !== "session\.data"/, "last useful activity must use worker output rather than raw runtime lifecycle events");
assert.match(home, /currentMissionTaskIds\.has\(event\.taskId\)/, "last useful activity must exclude prior Missions and sibling Threads");
assert.match(home, /candidate\.error\?\.trim\(\)/, "failed or blocked Task error text must be available as a human-readable reason");
assert.match(home, /Current Mission failure context/, "Simple Mode must expose actionable failure context without opening Workbench");
assert.match(home, /What happened/, "failure context should use product language rather than runtime terminology");
assert.match(home, /Last useful activity/, "failure context should include bounded recent worker output when available");
assert.match(home, /normalized\.length <= 320/, "last useful activity must remain bounded on the default Home surface");
assert.match(home, /task\.status === "failed" \|\| task\.status === "blocked" \|\| task\.status === "cancelled"/, "cancelled work must keep the aggregate Home status in the attention state");
assert.match(home, /message\.metadata\?\.missionId === latestMission\.id/, "current-work output must be scoped to the latest Mission instead of any prior Thread reply");
assert.match(home, /if \(!latestMission \|\| submitting\) return null;/, "a new follow-up must hide the previous Mission output while the new request is starting");
assert.match(home, /\[latestMission, messages, submitting\]/, "current output must react immediately when a follow-up starts or finishes");
assert.match(home, /setSubmitting\(true\);\s+setLastReport\(null\);/, "starting a new Mission must clear the previous transient report immediately");
assert.doesNotMatch(home, /find\(\(message\) => message\.role === "assistant"\)\?\.content/, "Home must not use an unscoped assistant reply as current Mission output");
assert.match(home, /api\.retryNode\(taskId\)/, "failed work must be retryable directly from Simple Mode");
assert.match(home, /"Retry"/, "Simple Mode must present a plain-language retry action");
assert.match(home, /task\.status === "blocked" && !approvalTaskIds\.has\(task\.id\)/, "retry must not bypass a pending approval gate for that task");
assert.match(home, /function prepareCancelledMissionFollowup\(\)/, "cancelled Missions must have a dedicated safe recovery path");
assert.match(home, /latestMission\.status !== "cancelled" \|\| !selectedThreadId/, "cancelled-Mission recovery must stay scoped to a selected Thread");
assert.match(home, /setGoal\(`Continue this work: \$\{latestMission\.goal\}`\)/, "cancelled recovery must prepare a fresh follow-up from the cancelled Mission goal");
assert.match(home, /latestMission\?\.status === "cancelled" && selectedThreadId/, "cancelled recovery must only appear for the selected Thread's latest cancelled Mission");
assert.match(home, /Continue this work/, "Simple Mode must offer a plain-language cancelled-Mission recovery action");
assert.match(home, /Chef is working/, "active work should collapse to a human-readable status");
assert.match(home, /Work complete/, "completed work should collapse to a human-readable status");
assert.doesNotMatch(home, /NodePalette|ChannelRooms|AgentContextInspector|Power Mode|PTY|sessionId/, "default home must not expose Workbench/runtime machinery");

assert.match(onboarding, /Tell Chef the outcome/, "onboarding should teach intent as the first action");
assert.match(onboarding, /Work starts automatically/, "onboarding must make the no-Run happy path explicit");
assert.match(onboarding, /Step in only when needed/, "onboarding should teach exception-driven intervention");
assert.match(onboarding, /type → send → watch → respond only if asked → result/, "onboarding should summarize the happy path in plain language");
assert.match(onboarding, /chef:intent-onboarding-complete/, "onboarding should be first-run and dismissible instead of permanently occupying Home");
assert.doesNotMatch(onboarding, /NodePalette|ChannelRooms|AgentContextInspector|Power Mode|PTY|sessionId/, "onboarding must teach the product without exposing runtime jargon");

assert.doesNotMatch(rooms, /chef:view-mode|mode === "power"|setEnabled/, "Rooms should be a Workbench capability instead of a legacy Power-mode capability");
assert.match(rooms, /if \(!open\) return;/, "closed Rooms should not poll their channel endpoint");
assert.match(rooms, /if \(!open \|\| !selectedChannel\)/, "closed Rooms should not poll message history");

const threadSendCalls = home.match(/sendThreadMessage\(/g) ?? [];
assert.equal(threadSendCalls.length, 1, "the default home should have one authoritative Thread-scoped Chef intent submission path");

console.log("intent-home-ui: ok — Chef keeps Thread-scoped intent, history, approvals, recovery, and Workbench progressive depth coherent");
